//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ukad_task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public long id_page { get; set; }
        public string url { get; set; }
        public Nullable<long> website { get; set; }
        public Nullable<long> current_speed { get; set; }
        public Nullable<long> min_speed { get; set; }
        public Nullable<long> max_speed { get; set; }
    
        public virtual website website1 { get; set; }
    }
}
